### ISSUE TITLE
support more rule protocols

### ISSUE THREAD

**Issue by prchiouatchts** [google/gonids#118]
When parsing suricata rules, the following errors were shown with a parsing error:

2019/12/10 12:06:57 [ERR] invalid character '6' for a rule protocol
alert ipv6 any any -> any any (msg:"SURICATA reserved field in Frag Header not zero"; decode-event:ipv6.fh_non_zero_reserved_field; classtype:protocol-command-decode; sid:2200095; rev:2;)
2019/12/10 12:06:57 [ERR] invalid character '2' for a rule protocol
alert ikev2 any any -> any any (msg:"SURICATA IKEv2 weak cryptographic parameters (Auth)"; flow:to_client; app-layer-event:ikev2.weak_crypto_auth; classtype:protocol-command-decode; sid:2224004; rev:2;)
2019/12/10 12:06:57 [ERR] invalid character '2' for a rule protocol
alert ikev2 any any -> any any (msg:"SURICATA IKEv2 unknown proposal"; flow:to_server; app-layer-event:ikev2.unknown_proposal; classtype:protocol-command-decode; sid:2224011; rev:1;)
2019/12/10 12:06:58 [ERR] invalid character '3' for a rule protocol
alert dnp3 any any -> any any (msg:"SURICATA DNP3 Length too small";        app-layer-event:dnp3.len_too_small; classtype:protocol-command-decode; sid:2270001; rev:3;)

It seems gonids didn't support parsing app protocol in the protocol field of a rule. Will this be supported in the future? Thanks!!

**Comment by duanehoward** [comment]
This seems straight forward. i believe the lexer validates that protocols contain only characters and `-` right now, we should be able to add number support to this.
