### ISSUE TITLE
can't parse pcre in suricata

### ISSUE THREAD

**Issue by chuanjiesun** [google/gonids#3]
the parser can't parse pcre in suricata rules,can add the item to parser?
the rule looks like below:
alert http $HOME_NET any -> $EXTERNAL_NET $HTTP_PORTS (msg:"ET CURRENT_EVENTS Request to malicious info.php drive-by landing"; flow:established,to_server; content:"/info.php?n="; http_uri; fast_pattern:only; content:!"&"; http_uri; content:!"|0d 0a|Referer|3a|"; **pcre:"/\/info.php\?n=\d/U";** classtype:trojan-activity; sid:2013010; rev:3; metadata:created_at 2011_06_10, updated_at 2011_06_10;)

**Comment by duanehoward** [comment]
Thanks for the report, it was a known gap that hadn't affected my use case before. I've added support. Please reopen if the new version doesn't work.

As a side note, I think the PCRE if the rule provided should probably be escaping the '/' in the uri, as well as dots, etc.:
  \/info\.php
