### ISSUE TITLE
Support for lexing \ at end of content

### ISSUE THREAD

**Issue by duanehoward** [google/gonids#35]
PR #29 added support for lexing escaped quotes in option values, however this broke lexing a specific case in contents where the content ends in a `\` like:
`content:"foo\";`

**Comment by duanehoward** [comment]
I haven't had a chance to figure out a simple fix here yet. Solution may end up changing the lexer state functions and then handling this case in the parser, as every solution I can think of requires a double-backup in the lexer. @clem1 any other ideas?

**Comment by clem1** [comment]
@duanehoward nope, all my "easy/quick" solutions would break something else. :-/
