### ISSUE TITLE
parse rule falied,invalid type '\v' for content type

### ISSUE THREAD

**Issue by chuanjiesun** [google/gonids#46]
parse the rule falied：
 **alert http $EXTERNAL_NET any -> $HOME_NET any (msg:"ET POLICY Java Url Lib User Agent Web Crawl"; flow:established,to_server; content:"Java/"; nocase; http_user_agent; pcre:/Java/\d\.\d/Vi"; threshold: type both, track by_src, count 10, seconds 60; reference:url,www.mozilla.org/docs/netlib/seealso/netmods.html; reference:url,doc.emergingthreats.net/2002945; classtype:attempted-recon; sid:2002945; rev:12; metadata:created_at 2010_07_30, updated_at 2010_07_30;)**
error is : invalid type '\v' for option content, how to solve this problem?

**Comment by duanehoward** [comment]
I'm assuming this is because your pcre is missing the beginning `"`
Probably you want `pcre:"/Java/\d.\d/Vi";`

I'm currently unable to test this though.

**Comment by duanehoward** [comment]
Looking at the upstream rule itself it does seem that this is syntactically incorrect, and based on the update metadata from emerging-threats it's been wrong for 9 years.

**Comment by chuanjiesun** [comment]
You are right, the rule is missing `"`, that's really an old mistake:smile:.
